version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=random_posts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "random_posts"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./static:/app/static
        - ./media:/app/media
      depends_on:
        - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py generate_fake_data && gunicorn --bind 0.0.0.0:8000 random_posts.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=random_posts.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],db

volumes:
  pgdata:

